personas:
  data_engineer:
    name: "Data Engineer Dave"
    interests:
      - "Data Engineering"
      - "Machine Learning"
      - "Big Data Processing"
      - "Cloud Architecture"
      - "Data Pipelines"
    needs:
      - "Technical documentation"
      - "Platform capabilities"
      - "Integration details"
      - "Pricing information"
      - "Performance benchmarks"
    goals:
      - "Evaluate data processing capabilities"
      - "Understand MLOps features"
      - "Compare pricing tiers"
      - "Find implementation examples"
      - "Access technical specifications" 